export const LOG_TYPE = {
  TRADE_PLAN: "TRADE_PLAN",
  TRADE_EXECUTION: "TRADE_EXECUTION",
  TRADE_ERROR: "TRADE_ERROR",
  DEPOSIT: "DEPOSIT",
  WITHDRAWAL: "WITHDRAWAL",
  TRADE_RETRY: "TRADE_RETRY",
};
